config:
  default:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_conversation_resolution: true
  studio-backend:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
  studio-ui:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
  snyk_check:
    state: enabled
    mode: selected
    selected_repos:
      - files-context
      - documents-context
      - external-validation-service
      - tcyran-test
    excluded_repos: []
    snyk_project_types:
      - golangdep
      - gomodules
      - gradleA
      - npm
      - pip
      - gradle
      - maven
      - pip
      - yarn
    snyk_contexts:
      - 'security/snyk (Hypatos)'
