config:
  default_branch_protection:
#     required_status_checks: null
#     enforce_admins: null
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
    required_conversation_resolution: true
#     restrictions: null
#     require_last_push_approval: true
  snyk_check:
    state: enabled
    mode: selected
    selected_repos:
      - tcyran-test
    excluded_repos: []
    snyk_contexts:
      - 'security/snyk (Hypatos)'
