config:
  default_branch_protection:
    required_status_checks: null
    enforce_admins: null
    required_pull_request_reviews:
      required_approving_review_count: 1
    restrictions: null
    require_last_push_approval: true
