config:
  default:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_conversation_resolution: true
      enforce_admins: true
  tcyran-test:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_conversation_resolution: true
      enforce_admins: true
  studio-backend:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_conversation_resolution: false        
  studio-ui:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_conversation_resolution: false
  enrichment-data-streams:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_conversation_resolution: false
  composite-enrichment-service:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_conversation_resolution: false
  enrichment-data-api:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_conversation_resolution: false
  hy-sandbox:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
      required_conversation_resolution: false
  snyk_check:
    state: enabled
    mode: all
    selected_repos: []
    excluded_repos:
      - enrichment-hub
      - enrichment-data-api
      - composite-enrichment-service
      - api-gateway-extauth
      - openai-kotlin
      - enrichment-service
      - enrichment-data-streams
      - document-api-internal
    snyk_project_types:
      - golangdep
      - gomodules
      - gradleA
      - npm
      - pip
      - gradle
      - maven
      - pip
      - yarn
      - poetry
    snyk_contexts:
      - 'security/snyk (Hypatos)'
