config:
  default:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_conversation_resolution: true
  studio-backend:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
  studio-ui:
    default_branch_protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
  snyk_check:
    state: enabled
    mode: all
    selected_repos: []
    excluded_repos: 
     - enrichment-hub
     - enrichment-data-api
     - composite-enrichment-service
     - api-gateway-extauth
     - openai-kotlin
     - enrichment-service
     - enrichment-data-streams
     - document-api-internal
    snyk_contexts:
      - 'security/snyk (Hypatos)'
